# Generated by Django 5.1.4 on 2024-12-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_schedule_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='created_by',
        ),
    ]
